In [1]:
# Numpy is numerical python
# We can have N-dimensional arrays in numpy and is called ndarray
# The dimension of ndarray is called rank
# Elements of ndarray should be of same type
# Shape defines the size of an array
# data type of elements in ndarray is represented by dtype object

In [2]:
import numpy as np

In [3]:
# Create an array of elements ranging from 0 to 19
array = np.arange(20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
# 1-D Array Addition
array_one = np.array([1, 2, 3, 4, 5])
array_two = np.array([6, 7, 8, 9, 10])
array_add=  array_one + array_two
array_add

array([ 7,  9, 11, 13, 15])

In [5]:
# NUMPY SUBTRACTION
array_sub = array_two - array_one
array_sub

array([5, 5, 5, 5, 5])

In [6]:
# NUMPY MULTIPLICATION
array_mult = array_one * array_two
array_mult

array([ 6, 14, 24, 36, 50])

In [7]:
# NUMPY DIVISION
array_division = array_two / array_one
array_division

array([6, 3, 2, 2, 2])

In [11]:
# NUMPY POWERS
array_square = array_one ** 2
print(array_square)
array_cube = np.power(array_one, 3)
print(array_cube)

[ 1  4  9 16 25]
[  1   8  27  64 125]


In [12]:
# NUMPY CONDITIONAL EXPRESSIONS
array_cond = array_two >= 3
array_cond

array([ True,  True,  True,  True,  True])

In [14]:
# 2-D NUMPY ADDITION
a = np.array([[3, 2], [1, 0]])
b = np.array([[2, 5], [3, 0]])
array_2d_add = a + b
array_2d_add

array([[5, 7],
       [4, 0]])

In [15]:
array_2d_sub = b - a
array_2d_sub

array([[-1,  3],
       [ 2,  0]])

In [16]:
array_2d_mult = a * b
array_2d_mult

array([[ 6, 10],
       [ 3,  0]])

In [18]:
array_2d_division = b / a
array_2d_division

/home/aifi/.local/lib/python2.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in divide
  """Entry point for launching an IPython kernel.


array([[0, 2],
       [3, 0]])

In [22]:
array_sh = np.array([[3,2,1], [6,5,4]])
array_sh.shape

(2, 3)

In [24]:
array_slice  = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array_slice[1::3])

[2 5 8]


In [25]:
array_slice_2d = np.array([[10, 11, 12, 13],
                          [14, 15, 16, 17],
                          [18, 19, 20, 21],
                          [22, 23, 24, 25 ]])
array_slice_2d[1:4, 2:4]

array([[16, 17],
       [20, 21],
       [24, 25]])

In [26]:
array_slice_3d = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]], 
                            [[20, 21, 22], [23, 24, 25], [26, 27, 28]], 
                            [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])

array_slice_3d[:2, 1:, :2]

array([[[13, 14],
        [16, 17]],

       [[23, 24],
        [26, 27]]])