In [1]:
import numpy as np

In [4]:
# np.arange(starting number, end number, step size)

arange1 = np.arange(1, 30, 4)
arange1

array([ 1,  5,  9, 13, 17, 21, 25, 29])

In [5]:
# 1-D Array of zeros
zeros_1d = np.zeros(3)
zeros_1d

array([0., 0., 0.])

In [6]:
# 2-D array of zeros
zeros_2d = np.zeros([3 , 4])
zeros_2d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
# 1-D array of ones
ones_1d = np.ones(3)
ones_1d

array([1., 1., 1.])

In [8]:
ones_2d = np.ones([3, 2])
ones_2d

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
empty_1d = np.empty(2)
empty_1d

array([5.73021895e-300, 4.63794013e-310])

In [18]:
empty_2d = np.empty([3, 2])
empty_2d

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
# full will fill the array with the given number
full_2d = np.full((2, 3), 4.15)
full_2d

array([[4.15, 4.15, 4.15],
       [4.15, 4.15, 4.15]])

In [21]:
# eye is identity matrix which will fill the diagonal with 1
eye2d = np.eye(3)
eye2d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
# The function 'linspace' returns evenly spaced numbers over a specified interval. 
# For example, the below function returns four equally spaced numbers between the interval 0 and 10.
linspace_1d = np.linspace(0,10,4)
linspace_1d

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [23]:
# To create a 2-D array, pass a sequence of lists to the array function.
arr_2d = np.array([(2,3,4), (5,6,7)])
arr_2d

array([[2, 3, 4],
       [5, 6, 7]])

In [26]:
# create randomn number
random_2d = np.random.random([2,3])
random_2d

array([[0.01296123, 0.47382604, 0.53244978],
       [0.21378252, 0.20627333, 0.62832226]])