In [8]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [7]:
#.reshape() makes the input variables 2-D (1 column vs many rows)
x =  np.array([21, 24, 27, 30, 33, 36, 39]).reshape(-1,1)
y = np.array([4, 7, 10, 8, 12, 11, 13])

print(x)
print(y)

[[21]
 [24]
 [27]
 [30]
 [33]
 [36]
 [39]]
[ 4  7 10  8 12 11 13]


In [9]:
# Create a linear regression model and fit the data
model = LinearRegression()
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [10]:
# Once the model is fit, we can get the results such as R-Squared value, Intercept & Co-efficients

# Find the R-Squared value
r_square = model.score(x, y)
print('R-Squared value is {}'.format(r_square))

R-Squared value is 0.822716346154


In [11]:
# Find the intercept
# The intercept (sometimes called the “constant”) in a regression model represents 
# the mean value of the response variable when all of the predictor variables 
# in the model are equal to zero.
intercept_val = model.intercept_
print('Intercept value is {}'.format(intercept_val))

Intercept value is -3.92857142857


In [12]:
#  Find the Slope or Co-efficient value
# Slope / co-eff value represents the y value increases by 0.44 units for 1 unit increase in x value.
slope = model.coef_
print('coefficient is {}'.format(slope))

coefficient is [0.44047619]


In [13]:
p = np.array([21, 24, 27, 30, 33, 36, 39]).reshape((-1, 1))
q = np.array([4, 7, 10, 8, 12, 11, 13]).reshape((-1, 1))
print(p)
print(q)

[[21]
 [24]
 [27]
 [30]
 [33]
 [36]
 [39]]
[[ 4]
 [ 7]
 [10]
 [ 8]
 [12]
 [11]
 [13]]


In [15]:
model_two = LinearRegression()
model_two.fit(p, q)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [16]:
rsquare_two = model.score(p, q)
print('rsquare is {}'.format(rsquare_two))

rsquare is 0.822716346154


In [17]:
intercept_two = model_two.intercept_
print('intercept is {}'.format(intercept_two))

intercept is [-3.92857143]


In [18]:
coeff_two = model_two.coef_
print('coefficient is {}'.format(coeff_two))

coefficient is [[0.44047619]]


### Predicting the response

In [19]:
# Once we have a satisfactory model, we can use it for predicting the response
# for a new set of regressors using .predict() method.
predicted_y = model.predict(x)
print('Predicted response is {}'.format(predicted_y))

Predicted response is [ 5.32142857  6.64285714  7.96428571  9.28571429 10.60714286 11.92857143
 13.25      ]


In [21]:
predicted_q = model_two.predict(p)
print("Predcited 2-D q response are: {}".format(predicted_q))

Predcited 2-D q response are: [[ 5.32142857]
 [ 6.64285714]
 [ 7.96428571]
 [ 9.28571429]
 [10.60714286]
 [11.92857143]
 [13.25      ]]


In [22]:
# Verifying the intercepts & slopes from the model.
pred_q = model_two.intercept_ + (model_two.coef_ * p)
print("Verifying the above reults here: {}".format(pred_q))

Verifying the above reults here: [[ 5.32142857]
 [ 6.64285714]
 [ 7.96428571]
 [ 9.28571429]
 [10.60714286]
 [11.92857143]
 [13.25      ]]
